name: Deploy Private GitHub repository to cPanel
on: 
  push:
    branches:
      - master
jobs:
  FTP-Deploy-Action:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3
      - name: 📂 Sync folders and files to the server
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ftp.bpnpdl.com.np
          username: mecomm@sandeep-sharma.me
          password: ${{ secrets.FTP_PASSWORD }}
